### ISSUE TITLE
Could i get Advance Swift pdf with English Language?

### ISSUE THREAD

**Issue by lawinko** [aozhimin/awesome-iOS-resource#1]

**Comment by aozhimin** [comment]
@lawinko http://download.csdn.net/download/yueenen/10217143?utm_source=bbsseo

**Comment by aozhimin** [comment]
@lawinko url: https://pan.baidu.com/s/1snp3PLz password: 8gwv

**Comment by SURYAKANTSHARMA** [comment]
could you please send in pdf format ? @aozhimin. i Download above file not able to open in mac.

**Comment by aozhimin** [comment]
@SURYAKANTSHARMA Okay, I have uploaded the PDF file, please download it.
url: https://pan.baidu.com/s/1hueWR9i password: zs9c

**Comment by SURYAKANTSHARMA** [comment]
@aozhimin  Thanks with Love bro.

**Comment by SURYAKANTSHARMA** [comment]
@aozhimin  Could you please arrange "data structures and algorithms made easy" Book ? PDF

**Comment by aozhimin** [comment]
@SURYAKANTSHARMA url: https://pan.baidu.com/s/1qZ4jlPq password: g7rv

**Comment by SURYAKANTSHARMA** [comment]
@aozhimin Thanks a lot.
